name: TheCrappiest-GrapplingHook
main: com.thecrappiest.grappling.GrapplingHook
version: 0.0.2
api-version: 1.16
softdepend: [WorldGuard]
commands:
  grappling:
    description: Default command for grappling hooks.
    usage: /<command>
    aliases: [gh, graphook, grapplinghook]